### DISCUSSION TITLE
Python durable funtion in kubernetes, baseUri of the management api payload cannot be configured

### DISCUSSION THREAD

**Discussion by realsenseme** [Azure/azure-functions-durable-extension#1921] [Q&A]
Hi All,

I have a durable function app with kubernetes as deployment target.  Function runtime is python.

```
Found Python version 3.9.6 (python3).

Azure Functions Core Tools
Core Tools Version:       3.0.3568 Commit hash: e30a0ede85fd498199c28ad699ab2548593f759b  (64-bit)
Function Runtime Version: 3.0.15828.0
```

If I trigger one of the registered orchestrator as below, the response with management apis has the baseUri with a missing path segment. (highlighted in green on the trigger url)
![durable](https://user-images.githubusercontent.com/57714323/129741034-19730808-abef-482a-884b-c75bc7e1887d.png)

How is the baseUrl evaluated and is there a way to configure the baseUri or atleast exclude the baseUrl and have only relative paths starting from /runtime in the response payload? 

Any inputs is highly appreciated :)

regards

**Comment by davidmrdavid** [comment]
Hi @realsenseme,

Thanks for reaching out!

Can you clarify what you mean by "the response management APIs has the baseURI with a missing path segment"? Is it that you expect to see a  `/pydurable-http/` segment in them? 

Also, do the links you receive 404 on a GET request, or do they work as-is?

Finally, and just for context, what version of `azure-functions-durable` are you using? Similarly, are you on extensionBundles v1 or v2? thanks!

**Reply by realsenseme** [reply]
@davidmrdavid  Let me answer the questions first:  azure-functions-durable : version 1.0.3
extensionBundle : v2

In the meantime I have tried a few things on my side and I can adjust the durabletask client response manually. but this is not we are looing for. 

To clarify my question further, I will explain my situation once more: 

We are deploying the durable function in AKS  with AppGw and Applicaiton Gateway Ingress controller to control incoming traffic where we are handling SSL termination.

And the ingress object to the durable client looks like this: 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "pydurable-http"
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: default
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
  labels:
    app: "pydurable-http"
spec:
  rules:
    - host: "<somethost>"
      http:
        paths:
          - path: /pydurable-http/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: "pydurable-http"
                port:
                  number: 80
```

The management APIs are by default having a context path : {host}/runtime/webhooks/....

Is it possible to configure the baseUrl for the runtime to be something like : {host}/pydurable-http/runtime/webhooks/.... so that they are accessible outside the cluster?  If so where can I configure? 

Thanks in advance for your support!
