### DISCUSSION TITLE
GitHub action freezes python durable functions

### DISCUSSION THREAD

**Discussion by phyrrus** [Azure/azure-functions-durable-extension#2083] [Q&A]
Hi there,

I've created a python azure durable function with a time trigger. The function works well, but when I try to use the code below to build and deploy the function via GitHub Actions, the function stops working. After that, if I try to manually trigger the function via VS Code I get the error message: 'Unexpected status code: 404'.  

Is this a bug or am I doing something wrong in the yml?

Thanks!

```
name: Build and deploy

on:
  [push]

env:
  AZURE_FUNCTIONAPP_NAME: function_name # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.8' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd
        
      #tests here

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
```
