### ISSUE TITLE
Add documentation for managing orchestrations/entities from external clients

### ISSUE THREAD

**Issue by wynandjordaan** [Azure/azure-functions-durable-extension#1600]
### Description
> We have run into an issue where Durable Functions cannot be run in Kubernetes when deployed. I am using the "func kubernetes deploy" command to generate the YAML file for deployment. By default the HTTP and non-HTTP functions are split up into two deployments or services. This creates a function whitelist in ENV variables like:
```
       env:
            - name: AzureFunctionsJobHost__functions__0
              value: GetWorkflowStatus_V1
            - name: AzureFunctionsJobHost__functions__1
              value: StartWorkflow_V1
            - name: AzureFunctionsJobHost__functions__2
              value: TerminateWorkflow_V1
            - name: AzureFunctionsJobHost__functions__3
              value: TriggerWorkflow_V1
```

### Expected behavior
> I expect that the HTTP functions should be able to run separate from the Orchestrator and Activities.

### Actual behavior
> Currently when deployed to Kubernetes we receive an error, when calling the StartNewAsync method, that the Orchestrator Function cannot be found or is disabled.

`Error: "The function 'RoadsideBatteryJobWorkflow' doesn't exist, is disabled, or is not an orchestrator function. Additional info: No orchestrator functions are currently registered!" "Asgard.Odin.Workflows.RoadsideBatteryJob.Triggers.StartJobWorkflow"
System.ArgumentException: The function 'RoadsideBatteryJobWorkflow' doesn't exist, is disabled, or is not an orchestrator function. Additional info: No orchestrator functions are currently registered!      
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskExtension.ThrowIfFunctionDoesNotExist(String name, FunctionType functionType) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\DurableTaskExtension.cs:line 1062
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationClient.StartNewAsync[T](String orchestratorFunctionName, String instanceId, T input) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableClient.cs:line 140
   at Asgard.Odin.Workflows.RoadsideBatteryJob.Triggers.StartJobWorkflow.Run(HttpRequestMessage request, String instanceId, IDurableClient orchestrationClient) in /src/dotnet-function-app/Asgard.Odin.Workflows.RoadsideBatteryJob/Triggers/StartJobWorkflow.cs:line 59`

### Known workarounds
> A workaround is to add the Orchestrator function in the whitelist on the HTTP functions deployment. This is not a great solution as any new deployments will have to be manually edited to be able to run.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: 2020/12/9 10:00pm (GMT +02:00)
- **Orchestration instance ID(s)**: b62119a9-3a14-4cd5-8dfd-35e5c624c47f
