### ISSUE TITLE
Unable to run .net core app Azure Durable Functions v3 in docker

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure/azure-functions-durable-extension#1720]
### Description
I am trying to implement a `docker-compose.yml` file to build a container for a .net core Azure Durable Function v3. The following code snippet is from the environment file i.e. `.env`:

```
AzureWebJobsStorage=MyConnectionString
AzureWebJobsDashboard=MyConnectionString
AzureWebJobsStorageQueue=MyAnotherConnectionString
```
This is how a part of the docker-compose file looks like:

```
  local.mydurablefunction:
    image: ${DOCKER_REGISTRY-}myfunction
    build:
      context: .
      dockerfile: src/MyFunction/Dockerfile
    ports:
      - 34080:34080   
    environment:
      - AzureWebJobsStorageQueue
      - AzureWebJobsDashboard
      - AzureWebJobsStorageQueue
  ```
When running docker-compose up I get the following error message:

> fail: Host.Startup[515] A host error has occurred during startup operation 'd8e39085-bed2-4f30-b80b-37d2fe1b286d'. System.InvalidOperationException: Unable to find an Azure Storage connection string to use for this binding. at Microsoft.Azure.WebJobs.Extensions.DurableTask.AzureStorageDurabilityProviderFactory.GetAzureStorageOrchestrationServiceSettings(String connectionName, String taskHub

This is how the function looks like:

### Expected behavior
The durable function should run without throwing the exception quoted above.

### Actual behavior
The exception quoted above keeps happening and the function never starts up.

### Relevant source code snippets

```csharp
[FunctionName("MyTrigger")]
        public async Task RunAsync(
            [QueueTrigger("queuename", Connection = "")] string metadataPayload,
            [DurableClient] IDurableOrchestrationClient starter,
            ILogger log,
            CancellationToken cancellationToken)
{
}

```
Somewhere in the function's body, we are calling a durable task which looks like the following code snippet:
```csharp
[FunctionName("Orchestrator")]
public async Task RunOrchestratorAsync(
    [OrchestrationTrigger] IDurableOrchestrationContext context,
    [DurableClient] IDurableOrchestrationClient orchestrationClient,
    ILogger log)
{
}
```
And this is the service dependency definition:
```json
{
  "dependencies": {
    "storage1": {
      "type": "storage",
      "connectionId": "AzureWebJobsStorageQueue"
    }
  }
}
```

### Known workarounds
None

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: Please see the following list:
```xml
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.4.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.12" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.13" />
```
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Programming language used**: C#

### Screenshots
N/A

### If deployed to Azure
N/A

**Comment by Arash-Sabet** [comment]
@cgillum @anthonychu  Is this issue something that you may be able to help escalate?

**Comment by cgillum** [comment]
@Arash-Sabet what do you have in your [host.json](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings#host-json) file? The primary way we discover the connection string is via the `connectionStringName` field. However, if you leave it blank we _should_ be defaulting to the value in `AzureWebJobsStorage`. I'm not sure if something about the docker environment might cause our defaulting behavior to act a bit differently.

**Comment by Arash-Sabet** [comment]
@cgillum This is what I have in host.json file:

```json
{
  "version": "2.0",
  "extensions": {
    "maxPollingInterval": "00:00:00.100"
  },
  "durableTask": {
    "hubName": "MillTasks",
    "maxQueuePollingInterval": "00:00:01",
    "storageProvider": {
      "partitionCount": 16,
      "maxQueuePollingInterval": "00:00:01"
    }
  }
}
```

**Comment by cgillum** [comment]
It looks like the host.json file is not consistent with the documented schema. However, that doesn't necessarily explain this error.

Try adding `connectionStringName` explicitly to your host.json to see if that resolves the issue. Here's an example that uses the correct schema:

```json
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "hubName": "MillTasks",
      "storageProvider": {
        "connectionStringName": "AzureWebJobsStorage",
        "partitionCount": 16,
        "maxQueuePollingInterval": "00:00:01"
      }
    }
  },
}
```

Also, I just now noticed that it looks like there might be a typo in your docker-compose file: You have defined `AzureWebJobsStorageQueue` twice. I wonder if you meant to include `AzureWebJobsStorage` in your `environment` block? I don't have experience with docker compose, but I wouldn't be surprised if this was the root cause of the problem. Here's what I'm guessing you meant for it to look like.

```yml
  local.mydurablefunction:
    image: ${DOCKER_REGISTRY-}myfunction
    build:
      context: .
      dockerfile: src/MyFunction/Dockerfile
    ports:
      - 34080:34080   
    environment:
      - AzureWebJobsStorage
      - AzureWebJobsDashboard
      - AzureWebJobsStorageQueue
```

(Also, I don't think you need `AzureWebJobsDashboard` - IIRC this is a legacy setting that has been deprecated)
