### ISSUE TITLE
Scaler for KEDA

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-durable-extension#911]
As we flesh out the Kubernetes storage backend, and even before, we should look at writing a scaler for KEDA to scale based on Durable Task tasks.  Had 2 customers ask me about Durable on KEDA / Kubernetes this week.  We have 2 options:

1. Build an 'built-in' scaler - these are little Go methods that know how to check for work required and pass metrics to KEDA for scaling.  Would require our scaling logic is written in Go
1. We have a PR right now for the ability to have "pluggable" scalers that could be in any language.  Architecture being you have to deploy a container that can talk via gRPC to pass back metrics to KEDA.  In this world I assume we could still use the Durable Task SDKs in .NET, but pass back via gRPC to KEDA

**Comment by cgillum** [comment]
Very cool.

Initially I'm thinking option 2 might make the most sense for us since it would allow us to ship updates to the Durable scaler independently of KEDA. Independent updates will likely be important since we plan to support multiple storage backends, and the logic/configuration we will need will be different for the various storage providers. Having that be an independent unit would allow us to be a bit more agile (enabling us to use our existing .NET assets would be nice as well).

For reference, our current .NET scaling logic when using the Azure Storage backend can be found [here](https://github.com/Azure/durabletask/blob/74a08cd47dfff75d396842cc5e74eff2ce0272ac/src/DurableTask.AzureStorage/Monitoring/DisconnectedPerformanceMonitor.cs#L87-L106).

**Comment by jeffhollan** [comment]
Nice. @Aarthisk @ahmelsayed @anirudhgarg as an FYI. This may be a good candidate to validate our external scaler support with a trigger source sometime before 1.0

**Comment by andrekiba** [comment]
Any news about this? :-)

**Comment by TsuyoshiUshio** [comment]
Hi @jeffhollan , @cgillum ,

I'll take this for our hack project next week as I talked with you guys. 
As you guys discussed, I'll implement with gRPC solution.  I have some questions. 


1.  Is my design the same as you thought?
   According to your conversation, I imagine something like this. 
   - Create a server that can talk with KEDA Durable Scale Controller talking with gRPC. It will be deployed on Kubernetes cluster as individual deployment. Hopefully deployed as a helm chart.
   - The server is written by .NET Core with Durable Task. 
   - KEDA implement scale controller that delegate scale decision to the server via gRPC. This is written by go.

In case it is different what you thought, please let me know. I'll follow your design. 

2. Repository of the Server
    Where should I create the repository for the Server implementation (.NET Core) It might not be a good idea put into the KEDA repo.  Maybe under the keda is the best place for it. However, Maybe I have no access right to create a repo under KEDA. Then I can create under Microsoft or Azure-Samples or my GItHub account then move under KEDA, if it become matured. 

3. The name of the server 
  The naming of the server. `keda-durable-scale-controller` sounds good? I'm not native speaking guy, so any suggestion is welcome.

**Comment by jeffhollan** [comment]
thanks @TsuyoshiUshio.  Adding @anirudhgarg as well who may be able to help answer questions while I'm out next week.

1. Yes I think you would be writing a .NET Core gRPC server that can use the KEDA extensibility model to publish metrics back to KEDA to drive scaling of durable.  I don't think you'll need to add *any* code to KEDA, as the KEDA piece you mentioned (a go thing that can speak gRPC to the .NET piece) is already supported from a feature @patnaikshekhar added [a few weeks back](https://github.com/kedacore/keda/pull/294) that should hook into what you need.
1. I would imagine this will eventually live in a repo like kedacore/durable-scaler or kedacore/scaler-extensions - not quite sure as we don't have one yet, but for now could just keep in a repo and we can merge it into the org when ready
1. Was thinking naming could be similar to how we do "azure-functions-durable-extension" so "keda-durable-scaler"
1. I think @anirudhgarg may be best place to start and can at least connect you with the right people.  Not sure what @patnaikshekhar bandwidth right now but he may be a good one as well if you opened a [WIP] pull request or something

**Comment by TsuyoshiUshio** [comment]
Thank you, Jeff, It is the perfect answer! :) Very good to know that KEDA already support the gRPC one. I read the PR, it is fantastic! It helps to reduce the workload! We'll have a look that and start writing keda-durable-scaler next week!

**Comment by TsuyoshiUshio** [comment]
Hello @anirudhgarg ,  

I have a question.
I try to define the Scale Object with the External Scaler support. 
https://github.com/kedacore/keda/pull/294

## Question 1: Which solution would you prefer?

I have three minimum configuration for Durable Functions Scale Server. I'd like to know which is the good design for the External Scaler support. Now I'm learning to design 2. Since I heard that one deployment need one durable scale server. Any comment is welcome.

### Design 1:  Define these on Scale Object. 
Define the Durable Functions related settings on the Scale Object.  

```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: durable-scaledobject
  namespace: keda-durable-test
  labels:
    deploymentName: keda-durable-csharp
spec:
  scaleTargetRef:
    deploymentName: keda-durable-csharp
triggers:
  - type: external
    metadata:
      scalerAddress: durable-external-scaler-service:5000 # Required
      connectionString: STORAGE_ACCOUNT_CONNECTION_STRING # Required
      taskHub: TASK_HUB_NAME # Required
      maxPollingIntervalMilliseconds : 30000 # Optional
```
### Design 2:   Configure settings by YAML file for the Durable Scale Server  as an environment variables. 

_keda_durable_scaler.yml_

```yaml
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: durable-scaledobject
  namespace: keda-durable-test
  labels:
    deploymentName: keda-durable-csharp
spec:
  scaleTargetRef:
    deploymentName: keda-durable-csharp
triggers:
  - type: external
    metadata:
      scalerAddress: durable-external-scaler-service:5000 # Required
```

_deployment.yml_

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-durable-external-scaler
  namespace: keda
spec:
  selector:
    matchLabels:
      service: keda-durable-external-scaler
  replicas: 1
  template:
    metadata:
      labels:
        service: keda-durable-external-scaler
    spec:
      containers:
      - image: tsuyoshiushio/durableexternalscaler:1.2
        name: scaler
        env:
        - name: CERT_PATH
          value: /certs
        - name:  CONNECTION_STRING
          value: <YOUR_STORAGE_ACCOUNT_CONNECTION_STRING>
        - name: TASK_HUB
          value: <YOUR_TASK_HUB_NAME> 
        - name: MAX_POLLING_INTERVAL
          value: <MAX_POLLING_INTERVAL_MILLISECOND> 
        volumeMounts:
        - name: certs
          mountPath: /certs
      volumes:
      - name: certs
        secret:
          secretName: keda-redis-external-scaler
```
